### ISSUE TITLE
Compiling against LibreSSL

### ISSUE THREAD

**Issue by lanodan** [ryd/chaosvpn#18]
```diff
diff --git a/crypto.c b/crypto.c
index e8b72d3..b917fb1 100644
--- a/crypto.c
+++ b/crypto.c
@@ -46,7 +46,7 @@ openssl dgst \

 */

-#if OPENSSL_VERSION_NUMBER < 0x10100000L
+#ifndef EVP_PKEY_get0_RSA
 #define EVP_PKEY_get0_RSA(a) ((a)->pkey.rsa)
 #endif
```

Note that I’m testing for the feature/function against itself not against version/name(what if *SSL removed it).

**Comment by haegar** [comment]
This does not work, as in openssl 1.1 EVP_PKEY_get0_RSA is not a define, so #ifndef would always be true.
